drop table if exists users, mpa, films_users, friendship, genre, film_genre, films cascade ;

  create table if not exists mpa(
  id integer not null primary key,
  mpa_name varchar
  );

  create table if not exists films(
  id integer GENERATED BY DEFAULT AS IDENTITY primary key,
  name varchar(255) not null,
  description varchar(200),
  release_date date,
  duration int,
  mpa_id int references mpa(id)
  );

  create table if not exists users(
  id integer GENERATED BY DEFAULT AS IDENTITY primary key,
  name varchar(100),
  email varchar(100) not null,
  login varchar(20) not null unique,
  birthday date
  );

  create table if not exists friendship(
  user_id integer not null references users(id) on delete cascade,
  friend_id integer not null references users(id) on delete cascade
  );

  create table if not exists genre(
  id integer not null primary key,
  genre_name varchar
  );

  create table if not exists film_genre(
  film_id integer not null references films(id) on delete cascade,
  genre_id integer not null references genre(id) on delete cascade
  );

  create table if not exists films_users(
  film_id integer not null references films(id) on delete cascade,
  user_id integer not null references users(id) on delete cascade,
  primary key (film_id, user_id)
  );